### ISSUE TITLE
Allow specification of target_commitish when creating a release

### ISSUE THREAD

**Issue by rgarcia** [aktau/github-release#12]
Currently it's not possible to pass this parameter when creating a release, so all releases by default will tag the current master branch.

**Comment by Tenzer** [comment]
Seeing that you have made commits to the project since the last comment, I wonder if this is something you could consider adding? :)

**Comment by aktau** [comment]
I'm not sure how to even get this to work, it keeps returning "422 Unprocessable Entity" entity for me.

Can you list your workflow where this could be handy? I'm interested.

Anyway, the change seems sane and conforms to the GH API so I"m merging it.

**Comment by Tenzer** [comment]
Hey @aktau. Thanks for merging it in. It seems like you need to either use the full commit SHA or a branch name as the target, you cannot just use part of a commit SHA.

I made a test repository at [github-release-test](https://github.com/Tenzer/github-release-test) with 5 empty commits, and a branch called [up-to-commit-4](https://github.com/Tenzer/github-release-test/commits/up-to-commit-4) which only holds the first 4 commits. Then I ran the following commands which gave the result you can see on the [releases page](https://github.com/Tenzer/github-release-test/releases):

```bash
$ export GITHUB_TOKEN="[...]"
$ export GITHUB_USER="Tenzer"
$ export GITHUB_REPO="github-release-test"
$ github-release release --tag no-parameters
$ github-release release --tag commit-2 --target 03807be7b0494b818bd94fab3339cf8a2455aa98
$ github-release release --tag commit-4-branch --target up-to-commit-4
```

I hope that explains it, otherwise let me know.
