### ISSUE TITLE
multi-platform releases

### ISSUE THREAD

**Issue by soniah** [aktau/github-release#29]
Hi Nicolas, thanks for writing github-release and sorry to raise an issue in order to ask a question.

I'm wondering if you have any pointers on how to do releases for multiple platforms (Linux, OSX, Windows). Do you just have multiple machines and run the build on each machine? I'm also looking at Travis-CI, see if I can use that.

Thanks, Sonia.

**Comment by aktau** [comment]
Well, if you look at the [Makefile](https://github.com/aktau/github-release/blob/master/Makefile) for github-release for example, you'll see that it generates executables for FreeBSD/Linux/OSX/Windows when `make release` is called. With Go, this is really easy, as you only need to set the `GOOS` and `GOARCH` (and `GOARM` if `GOARCH` is arm) environment variables and perform a go build. Since `github-release` is pure Go, that's all that's required. I hope that answers your question. otherwise, feel free to re-open the issue.

Also, for something more user-friendly and at the same time advanced, take a look at https://github.com/laher/goxc.

**Comment by soniah** [comment]
:+1:
