### ISSUE TITLE
Feature: built-in retry logic

### ISSUE THREAD

**Issue by fasterthanlime** [aktau/github-release#38]
After a week of releasing daily on github releases, I'm a bit frustrated with how often it returns 502 :(

I know it's absolutely not your fault, and ideally this would be a beautiful PR and not a feature request, but if anyone can find it in their heart to implement that before I get around to, it would be beautiful. :tada: 

I'm thinking maybe a `--tries` option (how many times to try) with a `--cooldown` option (how much to wait between tries) and have it only fail if all tries fail.

I'll probably implement it myself if no one beats me to the punch, but I just wanted to make sure @aktau thought this was a good idea / not outside the scope of github-release

**Comment by aktau** [comment]
First of all apologies for basically not looking at the open issues, and kudos on your forks which solves your and other people's issues.

**Comment by fasterthanlime** [comment]
@aktau no need to apologize :) You left a clean codebase for people to fork & expand to fit their needs, that's pretty good value for a $0 investment on the users' part!

**Comment by aktau** [comment]
Thanks, but I'll apologise anyway. Even if users don't invest anything, they still deserve to be treated with respect instead of being ignored (no matter if I rolled into a job that sucked up much more of my time). Doubly so when they aport code to fix their own issues (triply so if they do so to fix others' issues).

I couldn't help but chuckle when you complement the clean codebase. Many parts of it are anything but. I wish I had done better. Can't blame myself too much, I was less experienced, and like many things that turn out to be useful, github-release was written in a hurry to solve a need.

(*) Good thing I don't use acme(1), I could've been stoned for attempting to avoid clicking by clicking way more.

**Comment by mfonville** [comment]
@aktau thanks for picking up development again! :)
