### ISSUE TITLE
Pagination support for tags

### ISSUE THREAD

**Issue by jaymecd** [aktau/github-release#45]
I have over 100 tags in the repo, but see only 30 of them

**Comment by GabLeRoux** [comment]
I just hit that wall too
```bash
github-release info | grep name | wc -l
30
```

Can't see previous releases. I suppose there's something to do near this line:
https://github.com/aktau/github-release/blob/3512bf91cf6a70eff10f332e9604f228acb463c9/tags.go#L30

https://github.com/itchio/gothub/issues/1 talked about a workaround by adding `per_page=100`. The project I use this for has quite a lot of tags (more than 30).

**Comment by aktau** [comment]
The `per_page=100` thing would work for a while, but if a repo has more than 100 tags, you run into the same problem. I have a workaround (clever hack?) that does pagination transparently on the JSON stream for things calling `GithubGet`, so that the callers don't need to change.

Ping @mfonville and @fasterthanlime for some input.
