### ISSUE TITLE
Latest updates broke my automation built on top of github-release

### ISSUE THREAD

**Issue by jaytaylor** [aktau/github-release#64]
Hi,

Thank you for making this amazingly useful tool!

In the future, it'd be great if output formatting changes were avoided, or if a JSON output format were added.  Basically, the change of outputting `tags:` instead of `git tags:` broke part of a release pipeline that I maintain, and the subtlety of difference made it kind of painful to track down.

Thanks again for all your hard work on this.

Best,
Jay

**Comment by aktau** [comment]
Hi Jay,

First of all, thanks for the kinds words. Second: you're absolutely right. Breaking the output, even if it follows no sane convention, was gratuitous. There was no real reason for it apart from the fact that my current easthetic sensibility preferred a single word. I thought for just a moment that somebody may be relying on it, then discarded the idea as I thought the output formart looked sufficiently random to be "for humans only". As it turns out, that was wrong. Your suggestion of adding a JSON output format is a good one. When I get some time or a PR comes, I promise I'll prioritize it over other things (apart from breaking bugs).

Once again, apologies for the gratuitous change.

**Comment by jaytaylor** [comment]
Nicolas,

I'm glad we've been able to converge to the same wavelength on this, and am pleased the feedback seems to have been received in the spirit I'd intended!

Cheers,
Jay

**Comment by jaytaylor** [comment]
FYI I've gone ahead and opened PR #65 which addresses the JSON side of this.
